### ISSUE TITLE
Test yayını 

### ISSUE THREAD

**Issue by kumpinar** [boilerspixel/staj#2]
Bu ekranı test olarak bir yerde yayınlayabilir misin?

**Comment by kumpinar** [comment]
Bu konuda github pages iş görebilir. https://docs.github.com/en/github/working-with-github-pages

Ya da başka bir servis araştırabilirsin.

**Comment by boilerspixel** [comment]
Test ekranı olarak yayınlamak nasıl yapılıyor? Normal ekran paylaşımı gibi bir şey mi?

**Comment by kumpinar** [comment]
Şunu kastediyorum, mesela gizem.hithub.io adresine girince bu yaptığın sayfa çıksın.

**Comment by kumpinar** [comment]
Yukarda bahsettiğim dokumana baktın mı?
